const en = {
        //通用
        "maintitle":"Getbit",
        "plz":"please enter your ",
        "plz2":"please choose ",
        "edit":"Edit ",
        "forget":"Forget ",
        "type":"type",
        "tocopy":"Copied, sticky",
        'about_us':'About Us',
        //顶部栏
        "header_homepage":"Home",
        "header_c2ctrans":"Legal tender Trans",
        "header_cointrans":"Coin Trans",
        "header_contract":"swap",
        "header_fusion":"Fusion",
        'header_xinghuo':'Shark Plan',
        "header_contract":"Contract Trans",
        "header_assets":"Assets",
        "header_order":"Orders",
        "inviteBulletin":"inviteBulletin",
        "Partnership_plan":"Partnership plan",
        "Ore_pool":"Ore pool",
        "recharge":"Recharge",
        "cash":"Cash",
        "c2caccount":"C2C Account",
        "contractassets":"Contract Assets",
        "currententrust":"Current Entrust",
        "historyentrust":"History Entrust",
        "myinvite":"My Invite",
        "friminfo":"Frim Info",
        "accountsafety":"Account Safety",
        "cardsetting":"Card Setting",
        "loginout":"Sign Out",
        "sign":"Sign in ",
        "register":"Register",
        "language":"English",
        "more":"more",
        "top_helpcenter":"Help Center",
        'terms_and_conditions' : 'Terms and conditions',
        'user_agreement' : 'User Agreement',
        'privacy_policy' : 'Privacy Policy',
        'legal_description' : 'Legal description',
        'service_support' : 'service support',
        'trading_hall' : 'Trading hall',
        'coin_application' : 'Coin application',
        'official_announcement' : 'Official Announcement',
        'about' : 'About',
        'about_gnb' : 'About GNB',
        'terms_of_Service' : 'Terms of Service',
        'contact_us' : 'contact us',
        'customer_service_email' : 'Customer Service Email',
        'business_cooperation' : 'Business Cooperation',
        'digital_assets' : 'Digital Assets',
        'institutional_account' : 'Institutional Account',
        'download' : 'Download',
        'rate_standard' : 'Rate standard',
        'ht_introduction' : 'Platform Introduction',
        "fusionaccount":"Fusion Account",
        'myassets':'My Assets',
        //弹出提示
        'tip1':'Please confirm whether the email or mobile number is correct',
        'tip2':'Please enter 6-16 digit number and letter combination',
        'tip3':'Please enter 6-16 digit number or letter',
        'tip4':'Please enter your mobile number or email',
        'tip5':'Username cannot be empty',
        'tip6':'Please enter the verification code',
        'tip7':'Password cannot be empty',
        'tip8':'Payment Password cannot be empty',
        'tip9':'Password and payment password cannot be the same',
        'tip10':'Confirm that the login password is inconsistent with the login password',
        'tip11':'Modified success',
        'tip12':'Submitted, please wait for background audit',
        'tip13':'Binding success',
        'tip14':'Modified success',
        'tip15':'The new password is inconsistent with the confirm password',
        'tip16':'Payment password cannot be the same as login password',
        'tip17':'Password error',
        'tip18':'Shut down successfully',
        'tip19':'Please enter your mobile number',
        'tip20':'user does not exist',
        'tip21':'Please enter email',
        'tip22':'Get back to success',
        'tip23':'Recovery type does not exist',
        'tip24':'Please fill in the withdrawal address',
        'tip25':'Please fill in the note of withdrawal address',
        'tip26':'Please fill in the payment password',
        'tip27':'Add success',
        'tip28':'Address not selected',
        'tip29':'Successful mention of currency',
        'tip30':'Please enter your nickname',
        'tip31':'Wrong account or password',
        'register_tip':'login was successful',
        //绑定
        'bind':'binding ',
        //商户
        'alipay':'Alipay',
        'bank':'Bank',
        'wxpay':'Wxpay',
        'dealin':'Dealing',
        'submit_success':'Submit success',
        'completed':'Completed',
        'revoked':'Revoked',
        'revoke':'Revoke',
        //财务记录
        'assets_to_fusion':'Assets To Fusion',
        'fusion_to_assets':'Fusion To Assets',
        'assets_to_c2c':'Assets To C2C',
        'c2c_to_assets':'C2C To Assets',
        'success':'Success',
        'failed':'Failed',
        'confirmation':'Confirmation',
        'locking':'locking',
        //行情
        "index_excpairs":"Trans Group",
        "index_latestprice":"Latest price",
        "index_zhuangfu":"Today's Range",
        "index_maxprice":"High Price",
        "index_minprice":"Low Price",
        "index_24H":"24HVol",
        "index_24Htotal":"24HTurnover",
        //首页-下载
        'index_title1':'Global leading cryptocurrency decentralized trading platform',
        'index_title2':'Provide safe, stable and efficient asset trading services for one million professional cryptocurrency investors around the world',
        'index_tip1':' <span>Cutting edge safety protection</span><p>Advanced machine learning algorithm driven bank level SSL security technology can actively detect attacks and ensure the security of your assets and transactions</p>',
        'index_tip2':' <span>Lightning speed of trading</span><p>3 seconds to complete orders, comparable to the speed of traditional centralized exchange. With the advanced consensus mechanism of xinhuo, we can realize the double leap of performance and security</p>',
        'index_tip3':' <span>Global service support</span><p>XinHuo teams in the US, Luxembourg, China and Singapore provide you with 24 / 7 service support</p>',
        'index_title3':'Multi platform terminal transaction anytime, anywhere',
        'index_title4':'Covering multiple IOS and Android platforms, supporting full service functions',
        'index_title5':'IOS & Android Scan code download',
        'android_download':'Android Download',
        'iphone_download':'iphone Download',
        //登录
        "login_right":" <h1 style='color: white'>No Getbit Account yet?</h1><p style='color: white'>Register immediately and trade in Getbit blockchain</p><p style='color: white'>asset exchange.</p>",
        "login_toreg":"Free registration",
        "login":"Sign in ",
        "login_account":"Account",
        "login_accounts":"Please enter your login account",
        "psw":"Password",
        "login_psws":"Please enter your login password",
        "forget_password":"Forget password",
        "rememberme":"Remember Me",
        "login_tip2":"Sign up Success",
        //注册
        "regtime":"Register time",
        "register_right":"<p style='color: white'>Please make sure to choose them truthfully.</p><p style='color: white'>Please keep your Getbit account and login password properly.</p><p style='color: white'>Do not use the same login password as other web addresses.</p>",
        "register_tosign":"Login now",
        "register_area":"Area",
        "register_account":"Account",
        "imgcode":"Image Code",
        "phone":"Phone",
        "phone_verifty":"Code",
        "send":"Send Code",
        "confirm_password":"Confirm Psw",
        "deal_psw":"Assets Psw",
        "invitecode":"Invite Code",
        "reg_tip":"Please enter your Email or PhoneNumber",
        "noess":"Non essential",
        //公告
        "news":"News",
        "problem":"Problem",
        "active":"Actives",
        "createtime":"create on",
        "search":"Search",
        //忘记密码
        "email":"Email",
        "forget_tip":"reset password can't extract in 24 hours.",
        "next":"Next",
        "prev":"Previous",
        "newpassword":"New psw",
        "forgettype":"Retrieve Type",
        "phonetype":"Phone Number",
        "pkeytype":"private key",
        "emailtype":"Email",
        "submit":"Submit",
        //
        "cdeal_psw":"Comfirm Assets Psw",
        //资产
        "totalassets":"Total Assets",
        "proper_tip1":"hidden 0 nums coins",
        "searchcoin":"Search Coins",
        "record":"Record",
        "cashaddressmanage":"Cash Address Manage",
        "coins":"coins",
        "total":"total",
        "frozen":"frozen",
        "operation":"operation",
        "choosecoins":"Choose Coins",
        "cash_address":"Cash Address",
        "cash_address_note":"Cash Address Note",
        "cash_address_list":"Cash Address List",
        "del":"delete",
        "wallet_address":"Wallet Address",
        "copy":"click to copy",
        "distinguish":"Distinguish to recharge",
        "tip":"tip",
        "tip_recharge":" <p>1、The arrival time is usually 10-60 minutes. If you have any questions, please contact help@xinghuoex.com</p><p>2、After you recharge the above address of BTC, you need to confirm the whole BTC network node. In order to get the account quickly, you can pay a small fee to BTC network.</p><p>3、The minimum recharge amount is: 0.01btc your BTC address will not change, you can recharge repeatedly. If there is any change, we will notify you through website</p> <p>announcement or email.</p>",
        "tip_recharge1":"<p>1、The arrival time is usually 10-60 minutes. If you have any questions, please contact help@xinghuoex.com</p>",
        "tip_recharge2":" <p>2、After you recharge the above address of ",
        "tip_recharge3":", you need to confirm the whole ",
        "tip_recharge4":"network node. In order to get the account quickly, you can pay a small fee to",
        "tip_recharge5":"network.</p>",
        "tip_recharge6":"<p>3、The minimum recharge amount is: 0.01 ",
        "tip_recharge7":"your",
        "tip_recharge8":"address will not change, you can recharge repeatedly. If there is any change, we will notify you through website</p><p>announcement or email.</p>",
        "rechargerecord":"Recharge Record",
        "date":"date",
        "nums":"nums",
        "dnums":"nums",
        "count":"count",
        "status":"status",
        "fee":"fee",
        "fee_tip":"The network service charge shall be deducted from the account balance in priority, and when the balance is less than the network service charge, it shall be deducted from the withdrawal amount",
        "rc":" Record",
        "balance":"balance",
        "cash_tip":" <p>1. The minimum withdrawal quantity is 0.001 ",
        "cash_tip2":" </p><p>2. In order to ensure the safety of funds, when your account security policy changes, password changes, and the new address is used to withdraw currency,</p><p> we will conduct manual verification of the withdrawal currency,please wait patiently for the staff to contact by phone or email.</p><p>3. Please make sure the computer and browser are secure to prevent information from being tampered with or leaked.</p>",
        'cash_tip1':'Your withdrawal address is empty, click add address management',
        "transfer":"Transfer",
        "noaddress":"No Address",
        "fusion_transfer":"Fusion Transfer",
        //账户安全
        "safety":"Safety certification",
        "cert":"Certification",
        "safety_2":"Security level",
        "auth":"Authentication",
        "google":"Google Authenticator",
        "unbound":"Unbound",
        "tobinding":"To binding",
        "bound":"Bound",
        "No_modifiable":"Non modifiable",
        "KYC_nc":"KYC certification not completed",
        "KYC_hc":"KYC certification has completed",
        "inaudit":"In audit",
        "reexamine":"Reexamine",
        "tomodify":"To modify",
        "close":"Closed",
        "toclose":"To Close",
        'name':'Name',
        "safety_tip1":"<p>Internet accounts are at risk of being stolen. It is recommended that you change</p> <p> your password periodically to protect your account.</p>",
        "safety_tip2":"It is strongly recommended to open 3 safety certifications",
        "safety_tip3":"It is used to cash, retrieve password, modify security settings and manage API. It cannot be modified after activation",
        "safety_tip4":"It is used to collect verification SMS when cash, retrieving password, modifying security settings and managing API",
        "safety_tip5":"According to the requirements of policies and regulations, users are required to have real name authentication before conducting relevant transaction operations",
        "safety_tip6":"It is used to cash, retrieve password, modify security settings, and enter Google verification code when managing API",
        'login_history' : 'Login history',
        'security_settings_history' : 'Security settings history',
        'time' : 'Time',
        'login_method' : 'Login Method',
        'ip_address' : 'IP address',
        'security_setting' : 'Security setting',
        'low':'low',
        'med':'medium',
        'high':'high',
        //实名认证
        "auth_name":"Real Name",
        "auth_type":"Authentication type",
        "auth_type_1":"Personal",
        "auth_type_2":"Company",
        "auth_number":"ID card Number",
        "auth_sfzzm":"Upload ID card Front",
        "auth_sfzfm":"upload ID card Back",
        "auth_scsfz":"Holding ID card",
        "auth_tip":"  <p>Clear face without occlusion</p> <p>All ID cards are clear and unobstructed</p><p>All hands and arms are exposed</p>",
        //重置密码
        "resetpsw_tip":"Please Enter Your Old Password",
        "resetpsw":"Reset Password",
        "resetdpsw":"Reset Assets Psw",
        "newpsw":"New Psw",
        //重置支付密码
        "resetdpsw_tip":"Please Enter Your Old Password",
        //商户信息
        "pdegree":"Praise degree",
        "transtimes":"Transaction times",
        "histurnover":"Historical turnover",
        "enumber":"Evaluation number",
        "buy_adv":"Purchase advertisement",
        "sell_adv":"Advertising for sale",
        "firm_coin":"Coins",
        "firm_scoin":"Currency of collection",
        "price":"Pirce",
        "firm_translimit":"Trading limit",
        "firm_transtype":"Trading Type",
        "firm_updatetime":"UpdateTime",
        "firm_status":"Status",
        //订单
        "all":"all",
        "buy":"buy",
        "sell":"sell",
        "nodata":"No Data",
        "excpairs":"Transaction Group",
        "excpairsarea":"Transaction Area",
        "transtype":"Transaction Type",
        "deal":"Deal",
        "nodeal":"No Deal",
        //费率标准
        'rate_description' : 'Rate description',
        'transaction_rate' : 'Transaction rate',
        'withdrawal_rate' : 'Withdrawal rate',
        'currency_pair' : 'Currency pair',
        'buy_fee' : 'Buying fee',
        'sell_fee' : 'Selling fee',
        'min_cash_nums' : 'Minimum withdrawal amount',
        'cash_fee' : 'Cash withdrawal fee',
        'rate_tip1':'Recharge: Free。',
        'rate_tip2':'Trans:0.1% transaction fee for ordinary users (deducting received assets).',
        'rate_tip3':'Cash: Service charge for withdrawal will be adjusted regularly according to the actual situation of the block',
        //我的邀请码
        'invite_title': '<h1>Getbit super Commission</h1><h2>Invite friends to trade and easily get 20% commission back</h2>',
        'mywayofsharing' : 'My way of sharing',
        'qrposter' : 'Exclusive QR code poster',
        'view_exclusive_posters' : 'View exclusive posters',
        'exclusive_invitation_code' : 'Exclusive invitation code',
        'exclusive_registration_link' : 'Exclusive registration link',
        'total_invitations' : 'Total number of invitations',
        'invitation_record' : 'Invitation record',
        'invitee_account' : 'Invitee account',
        'registration_time' : 'Registration time',
        'remarks':'remarks',
        //谷歌绑定
        'safety_verification' : 'safety verification',
        'bind_google_captcha' : 'Bind Google Captcha',
        'off_google_captcha':'Google Captcha off',
        'google_captcha':'Google Captcha',
        'google_secretkey':'Secret Key',
        'copy_google_secretkey':'Copy Secret Key',
        'bind_goole_tips_1' : 'Google Authenticator is a dynamic password tool that works like SMS dynamic verification. Generate a dynamic verification code every 30s after binding. The verification code can be used to log in, withdraw cash, and modify security settings.',
        'bind_goole_tips_2' : 'Double verification can protect your account more securely, and double verification without opening does not affect normal transactions. We provide two binding methods for users, users can choose and operate according to the process.',
        'bind_goole_tips_3' : 'Bind Google Authenticator',
        'bind_goole_tips_4' : "IOS users log in to the App Store to search for 'Authenticator' downloads.",
        'bind_goole_tips_5' : 'Android users log in to the app store or use the mobile browser to search for "Google Authenticator" download',
        'bind_goole_tips_6' : 'Add the following new key and back up in the new Google Authenticator',
        'bind_goole_tips_7' : 'Open Google Authenticator, scan the QR code below or manually enter the following key to add a verification token.',
        'bind_goole_tips_8' : 'The key is used to retrieve the Google Authenticator when the phone is replaced or lost. Be sure to save the following key backup before binding.',
        'bind_goole_tips_9' : 'Please enter Google verification code',
        'bind_goole_tips_10':'Add the following new keys to the new Google verifier and back them up',
        //wap
        'phonenumber':'Cell-phone number',
        'wap_reg_title':'Registration',
        'wap_reg_tip1':'Register with a common mobile phone number, more convenient',
        'wap_reg_tip2':'Consent of the registered representative',
        'wap_reg_tip3':'《User agreement of the platform》',
        'wap_reg_tip4':'Already have an account?',
        'sms_code':'SMS verification code',
        'wap_reg_tip5':'Verification code has been sent to your phone',
        'wap_reg_tip6':'No verification code received?',
        'wap_reg_title1':'Create password',
        'wap_reg_tip7':'Create a login password to enhance asset security for login accounts',
        'wap_reg_title2':'Create payment password',
        'wap_reg_tip8':'Create payment password to enhance asset security',
        'wap_reg_title3':'Invitation code',
        'wap_reg_tip9':'Please enter the correct invitation code format',
        'wap_reg_complete':'Completion of registration',
        'wap_reg_tip10':'Please enter 6-16 alphanumeric combination',
        'wap_reg_tip11':'Please confirm the login password',
        'wap_reg_tip12':'Please enter 6-digit pure digital payment password',
        'wap_reg_tip13':'Please confirm the payment password',
        'wap_reg_tip14':'Please enter the invitation code'
}

