const zhCn= {
    //通用
    "maintitle":"Getbit交易所",
    "plz":"请输入",
    "plz2":"请选择",
    "edit":"修改",
    "forget":"忘记",
    "type":"类型",
    "tocopy":"已复制，可黏贴",
    'about_us':'关于我们',
    //顶部栏
    "header_homepage":"首页",
    "header_c2ctrans":"法币交易",
    "header_cointrans":"币币交易",
    "header_contract":"永续合约",
    'header_xinghuo':'狂鲨计划',
    "header_fusion":"聚变交易",
    "inviteBulletin":"邀请榜",
    "Partnership_plan":"合伙人计划",
    "Ore_pool":"矿池",
    "header_assets":"资产",
    "header_order":"订单",
    "recharge":"充币",
    "cash":"提币",
    "c2caccount":"法币资产",
    "contractassets":"合约资产",
    "currententrust":"当前委托",
    "historyentrust":"历史委托",
    "myinvite":"我的邀请码",
    "friminfo":"商户信息",
    "accountsafety":"账号安全",
    "cardsetting":"个人设置",
    "loginout":"退出",
    "sign":"登录",
    "register":"注册",
    "language":"简体中文",
    "more":"查看更多",
    "top_helpcenter":"帮助中心",
    
    'download' : '客户端下载',
    'join_us' : '加入我们',
    'terms_and_conditions' : '条款说明',
    'user_agreement' : '用户协议',
    'privacy_policy' : '隐私条款',
    'legal_description' : '法律说明',
    'service_support' : '服务支持',
    'trading_hall' : '交易大厅',
    'coin_application' : '上币申请',
    'official_announcement' : '官方公告',
    'terms_of_Service' : '服务条款',
    'about' : '关于',
    'about_gnb' : '关于GNB',
    'contact_us' : '联系我们',
    'customer_service_email' : '客服邮箱',
    'business_cooperation' : '商务合作',
    'digital_assets' : '数字资产',
    'ht_introduction' : '平台介绍',
    'rate_standard' : '费率标准',
    "fusionaccount":"聚变账户",
    'myassets':'我的资产',
   //弹出提示
    'tip1':'请确认邮箱或手机号码是否正确',
    'tip2':'请输入“6-16位数字与字母组合',
    'tip3':'请输入“6-16位数字或字母',
    'tip4':'请输入手机号或者邮箱',
    'tip5':'用户名不能为空',
    'tip6':'请输入验证码',
    'tip7':'密码不能为空',
    'tip8':'支付密码不能为空',
    'tip9':'密码与支付密码不能相同',
    'tip10':'确认登录密码与登录密码不一致',
    'tip11':'修改成功',
    'tip12':'已提交，请等待后台审核',
    'tip13':'绑定成功',
    'tip14':'修改成功',
    'tip15':'新密码与确认密码不一致',
    'tip16':'支付密码与不能与登录密码一致',
    'tip17':'密码错误',
    'tip18':'关闭成功',
    'tip19':'请输入手机号',
    'tip20':'用户不存在',
    'tip21':'请输入邮箱',
    'tip22':'找回成功',
    'tip23':'找回类型不存在',
    'tip24':'请填写提现地址',
    'tip25':'请填写提现地址备注',
    'tip26':'请填写支付密码',
    'tip27':'添加成功',
    'tip28':'地址未选择',
    'tip29':'提币成功',
    'tip30':'请输入昵称',
    'tip31':'账号或密码错误',
    'register_tip':'注册成功',
    //绑定
    'bind':'绑定',
    //商户
    'alipay':'支付宝',
    'bank':'银行',
    'wxpay':'微信',
    'dealin':'成交中',
    'submit_success':'提交成功',
    'completed':'已完成',
    'revoked':'已经撤销',
    'revoke':'下线',
    //财务记录
    'assets_to_fusion':'币币账户划入聚变账户',
    'fusion_to_assets':'聚变账户划出币币账户',
    'assets_to_c2c':'币币账户划入C2C账户',
    'c2c_to_assets':'C2C账户划出币币账户',
    'success':'成功',
    'failed':'失败',
    'confirmation':'确认中',
    'locking':'锁定',
    //行情
    "index_excpairs":"交易对",
    "index_latestprice":"最新价格",
    "index_zhuangfu":"今日涨幅",
    "index_maxprice":"最高价格",
    "index_minprice":"最低价格",
    "index_24H":"24H量",
    "index_24Htotal":"24H成交额",
    //首页-下载
    'index_title1':'全球领先的加密货币去中心化交易平台',
    'index_title2':'为全球100万的专业加密货币投资者提供安全、稳定、高效的资产交易服务',
    'index_tip1':' <span>尖端安全防护</span><p>先进机器学习算法驱动的银行级SSL安全技术，可主动检测攻击，保证您的资产和交易安全</p>',
    'index_tip2':' <span>闪电般的交易速度</span><p>3 秒完成订单，与传统中心化交易所媲美的速度。凭借 Getbit交易所 的先进共识机制，实现性能与安全双重飞跃</p>',
    'index_tip3':' <span>全球服务支持</span><p>遍布美国、卢森堡、中国和新加坡的 Getbit交易所 团队，为您提供全天候的服务支持</p>',
    'index_title3':'随时随地 多平台终端交易',
    'index_title4':'覆盖iOS、Android多个平台，支持全业务功能',
    'index_title5':'IOS & Android 扫码下载',
    'android_download':'Android 下载',
    'iphone_download':'iphone 下载',

    //登录
    "login_right":" <h1 style='color: white'>还没有<br/>Getbit交易所账号?</h1><p style='color: white'>立即注册,在Getbit交易所区块链资产交易所进行交易。</p>",
    "login_toreg":"免费注册",
    "login":"登录 ",
    "login_account":"账号",
    "login_accounts":"请输入您的登录账号",
    "psw":"登录密码",
    "login_psws":"请输入您的登录密码",
    "forget_password":"忘记密码",
    "rememberme":"记住账户名",
    "regtime":"注册时间",
    "login_tip2":"登录成功",
    //注册
    "register_right":"  <p style='color: white'>手机号与邮箱注册后不可修改,请务必如实选择。</p><p style='color: white'>验证邮件可能会被误判为垃圾邮件，请注意查收。</p><p style='color: white'>请妥善保存您的Getbit交易所账号及登录密码。</p><p style='color: white'>请勿和其他网址使用相同的登录密码。</p>",
    "register_tosign":"立即登录",
    "register_area":"区号",
    "register_account":"账号",
    "phone":"手机",
    "imgcode":"图片验证",
    "phone_verifty":"验证码",
    "send":"发送验证码",
    "confirm_password":"确认登录密码",
    "deal_psw":"支付密码",
    "invitecode":"邀请码",
    "reg_tip":"请输入邮箱或手机号",
    "noess":"非必填",
    //公告
    "news":"官方公告",
    "problem":"常见问题",
    "active":"最近活动",
    "createtime":"文章创建于",
    "search":"搜索",

    //忘记密码
    "email":"邮箱",
    "forget_tip":"重置密码后24小时禁止提币。",
    "next":"下一步",
     "prev":"上一步",
    "newpassword":"新密码",
    "forgettype":"找回类型",
    "phonetype":"电话找回",
    "pkeytype":"私钥找回",
    "emailtype":"邮箱找回",
    "submit":"提交",
    //忘记支付密码
    "cdeal_psw":"确认支付密码",

    //资产
    "totalassets":"总资产折合",
    "proper_tip1":"隐藏数量为零的币种",
    "searchcoin":"搜索币种",
    "record":"财务记录",
    "cashaddressmanage":"提现地址管理",
    "coins":"币种",
    "total":"可用",
    "frozen":"冻结",
    "operation":"操作",
    "choosecoins":"选择币种",
    "cash_address":"提现地址",
    "cash_address_note":"提现地址备注",
    "cash_address_list":"提现地址列表",
    "del":"删除",
    "wallet_address":"钱包地址",
    "copy":"点击复制",
    "distinguish":"扫码充币",
    "tip":"温馨提示",
    "tip_recharge1":"  <p>1、到賬時間一般是10分鐘-60分鐘，如有疑問請聯繫help@gws.plus/</p>",
    "tip_recharge2":"  <p>2、您充值",
    "tip_recharge3":"上述地址後，需要整個",
    "tip_recharge4":"網絡節點的確認，為了快速到賬，您可以向",
    "tip_recharge5":"網絡支付少量的手續費。</p>",
    "tip_recharge6":"<p>3、最小充值金額是：0.01",
    "tip_recharge7":"您的",
    "tip_recharge8":"地址不會改變，可以重複充值，如有更改，我們會通過網站公告或郵件通知您。</p>",
    "rechargerecord":"充币记录",
    "date":"时间",
    "nums":"数量",
    "dnums":"到账数量",
    "count":"确认数",
    "status":"状态",
    "fee":"手续费",
    "fee_tip":"网络手续费优先从账户余额中扣除，当余额不足网络手续费时则从提币数量中扣除",
    "rc":"记录",
    "balance":"可用",
    "cash_tip":" <p>1. 最小提币数量为：0.001",
    "cash_tip2":"</p><p>2. 为保障资金安全，当您账户安全策略变更、密码修改、使用新地址提币，我们会对提币进行人工审核，请耐心等待工作人员电话或邮件联系。</p> <p>3. 请务必确认电脑及浏览器安全，防止信息被篡改或泄露。</p>",
    "cash_tip1":"您的提币地址为空，点击地址管理添加哦",
    "transfer":"划转",
    "fusion_transfer":"聚变划转",
    "noaddress":"暂无地址",
    //账户安全
    "safety":"安全认证",
    "cert":"认证",
    "safety_2":"安全级别",
    "auth":"实名认证",
    "google":"Google验证",
    "unbound":"未绑定",
    "tobinding":"去绑定",
    "bound":"已绑定",
    "No_modifiable":"不可修改",
    "KYC_nc":"未完成KYC认证",
    "KYC_hc":"已完成KYC认证",
    "inaudit":"审核中",
    "reexamine":"重新审核",
    "tomodify":"去修改",
    "toclose":"去关闭",
    "close":"已关闭",
    'name':'姓名',
    "safety_tip1":"互联网账号存在被盗风险，建议您定期更改密码以保护账户安全。",
    "safety_tip2":"强烈建议开启3项安全认证",
    "safety_tip3":"用于提币、找回密码、修改安全设置、管理API时使用，激活后不可修改",
    "safety_tip4":"用于提币、找回密码、修改安全设置、管理API时用以收取验证短信",
    "safety_tip5":"根据政策法规要求，请用户务必实名认证，才能进行相关交易操作",
    "safety_tip6":"用于提币、找回密码、修改安全设置、管理API时用以输入谷歌验证码",
    'login_history' : '登录历史',
    'security_settings_history' : '安全设置历史',
    'time' : '时间',
    'login_method' : '登录方式',
    'ip_address' : 'IP地址',
    'security_setting' : '安全设置',
    'low':'低',
    'med':'中',
    'high':'高',
    //实名认证
    "auth_name":"真实姓名",
    "auth_type":"认证类型",
    "auth_type_1":"个人",
    "auth_type_2":"企业",
    "auth_number":"证件号码",
    "auth_sfzzm":"上传身份证正面照",
    "auth_sfzfm":"上传身份证反面照",
    "auth_scsfz":"手持身份证",
    "auth_tip":"  <p>脸部清晰无遮挡</p> <p>身份证全部清晰无遮挡</p><p>完全露出双手手臂</p>",
    //重置密码
    "resetpsw_tip":"请输入原登录密码",
    "resetpsw":"修改登录密码",
    "resetdpsw":"修改支付密码",
    "newpsw":"新密码",
    //重置支付密码
    "resetdpsw_tip":"请输入原支付密码",
    //商户信息
    "pdegree":"好评度",
    "transtimes":"交易次数",
    "histurnover":"历史成交额",
    "enumber":"评价数",
    "buy_adv":"购买广告",
    "sell_adv":"出售广告",
    "firm_coin":"币种",
    "firm_scoin":"收款币种",
    "price":"单价",
    "firm_translimit":"交易限额",
    "firm_transtype":"交易方式",
    "firm_updatetime":"最后更新时间",
    "firm_status":"广告状态",
    //订单
    "all":"全部",
    "buy":"买单",
    "sell":"卖单",
    "nodata":"无数据",
    "excpairs":"交易对",
    "excpairsarea":"交易区",
    "transtype":"交易类型",
    "deal":"已成交",
    "nodeal":"未成交",
    //费率标准
    'rate_description' : '费率说明',
    'transaction_rate' : '交易费率',
    'withdrawal_rate' : '提现费率',
    'currency_pair' : '币对',
    'buy_fee' : '买单手续费',
    'sell_fee' : '卖单手续费',
    'min_cash_nums' : '最小提币数量',
    'cash_fee' : '提币手续费',
    'rate_tip1':'充币: 免费。',
    'rate_tip2':'交易: 普通用户0.1% 的交易手续费（扣除收取到的资产）。',
    'rate_tip3':'提现: 提现手续费将会根据区块实际情况定期调整',
    //我的邀请码
    'invite_title': '   <h1>Getbit交易所超级返佣</h1><h2>邀请好友交易，轻松获得 20% 返佣</h2>',
    'mywayofsharing' : '我的分享方式',
    'qrposter' : '专属二维码海报',
    'view_exclusive_posters' : '查看专属海报',
    'exclusive_invitation_code' : '专属邀请码',
    'exclusive_registration_link' : '专属注册链接',
    'total_invitations' : '邀请总人数',
    'invitation_record' : '邀请记录',
    'invitee_account' : '被邀请人账号',
    'registration_time' : '注册时间',
    'remarks':'备注',
    //谷歌绑定
    'safety_verification' : '安全验证',
    'bind_google_captcha' : '绑定谷歌验证码',
    'off_google_captcha':'关闭谷歌验证码',
    'google_captcha':'谷歌验证码',
    'google_secretkey':'密钥',
    'copy_google_secretkey':'复制密钥',
    'bind_goole_tips_1' : '谷歌验证器是一款动态口令工具，工作原理类似短信动态验证。绑定后每30s生成一个动态验证码，验证码可用于登录、提现、修改安全设置',
    'bind_goole_tips_2' : '双重验证可以更安全的保护您的账户，未开启双重验证不影响正常的交易。我们提供两种绑定方式给用户，用户可以自行选择并按流程操作',
    'bind_goole_tips_3' : '绑定谷歌验证器',
    'bind_goole_tips_4' : "IOS用户登录App Store搜索'Authenticator'下载。",
    'bind_goole_tips_5' : '安卓用户登录应用商店或使用手机浏览器搜索"谷歌验证器"下载',
    'bind_goole_tips_6' : '在新谷歌验证器中添加以下新密钥并备份',
    'bind_goole_tips_7' : '打开谷歌验证器，扫描下方二维码或手动输入下述密钥添加验证令牌。',
    'bind_goole_tips_8' : '密钥用于手机更换或遗失时找回谷歌验证器，绑定前请务必将下述密钥备份保存。',
    'bind_goole_tips_9' : '请输入谷歌验证码',
    'bind_goole_tips_10':'在新谷歌验证器中添加以下新密钥并备份',
    //wap
    'phonenumber' : '手机号',
    'wap_reg_title' : '手机号注册',
    'wap_reg_title_2' : '邮箱注册',
    'wap_reg_tip1' : '使用常用手机号进行注册，更便捷',
    'wap_reg_tip_1' : '使用常用邮箱进行注册，更便捷',
    'wap_to_phone' : '去用手机注册',
    'wap_to_email' : '去用邮箱注册',
    'wap_reg_tip2' : '注册代表同意',
    'wap_reg_tip3' : '《本平台用户协议》',
    'wap_reg_tip4' : '已有账号？',
    'sms_code' : '短信验证码',
    'sms_code2' : '邮箱验证码',
    'wap_reg_tip5' : '验证码已发送到你的手机',
    'wap_reg_tip_5' : '验证码已发送到你的邮箱',
    'wap_reg_tip6' : '没有收到验证码？',
    'wap_reg_title1' : '创建密码',
    'wap_reg_tip7' : '创建登录密码可增强资产安全性，用于登录账号',
    'wap_reg_title2' : '创建支付密码',
    'wap_reg_tip8' : '创建支付密码可增强资产安全性',
    'wap_reg_title3' : '邀请码',
    'wap_reg_tip9' : '请输入正确的邀请码格式',
    'wap_reg_complete' : '完成注册',
    'wap_reg_tip10' : '请输入6-16位字母数字组合',
    'wap_reg_tip11' : '请确认登录密码',
    'wap_reg_tip12' : '请输入6位纯数字',
    'wap_reg_tip13' : '请确认支付密码',
    'wap_reg_tip14' : '请输入邀请码'
}

export default zhCn

