const zhTw = {
    //通用
        "maintitle":"Getbit交易所",
        "plz":"請輸入",
        "plz2":"請選擇",
        "edit":"修改",
        "forget":"忘記",
        "type":"類型",
        "tocopy":"已復制，可黏貼",
        "about_us":"關於我們",
        //頂部欄
        "header_homepage":"首頁",
        "header_c2ctrans":"法幣交易",
        "header_cointrans":"幣幣交易",
        "header_contract":"永續合約",
        "header_xinghuo":"狂鯊計劃",
        "header_fusion":"聚變交易",
        "inviteBulletin":"邀請榜",
        "Partnership_plan":"合夥人計劃",
        "Ore_pool":"礦池",
        "header_assets":"資產",
        "header_order":"訂單",
        "recharge":"充幣",
        "cash":"提幣",
        "c2caccount":"法幣資產",
        "contractassets":"合約資產",
        "currententrust":"當前委托",
        "historyentrust":"歷史委托",
        "myinvite":"我的邀請碼",
        "friminfo":"商戶信息",
        "accountsafety":"賬號安全",
        "cardsetting":"個人設置",
        "loginout":"退出",
        "sign":"登錄",
        "register":"註冊",
        "language":"簡體中文",
        "more":"查看更多",
        "top_helpcenter":"幫助中心",

        "download" :"客戶端下載",
        "join_us" :"加入我們",
        "terms_and_conditions" :"條款說明",
        "user_agreement" :"用戶協議",
        "privacy_policy" :"隱私條款",
        "legal_description" :"法律說明",
        "service_support" :"服務支持",
        "trading_hall" :"交易大廳",
        "coin_application" :"上幣申請",
        "official_announcement" :"官方公告",
        "terms_of_Service" :"服務條款",
        "about" :"關於",
        "about_gnb" :"關於GNB",
        "contact_us" :"聯系我們",
        "customer_service_email" :"客服郵箱",
        "business_cooperation" :"商務合作",
        "digital_assets" :"數字資產",
        "ht_introduction" :"平臺介紹",
        "rate_standard" :"費率標準",
        "fusionaccount":"聚變賬戶",
        "myassets":"我的資產",
        //彈出提示
        "tip1":"請確認郵箱或手機號碼是否正確",
        "tip2":"請輸入“6-16位數字與字母組合",
        "tip3":"請輸入“6-16位數字或字母",
        "tip4":"請輸入手機號或者郵箱",
        "tip5":"用戶名不能為空",
        "tip6":"請輸入驗證碼",
        "tip7":"密碼不能為空",
        "tip8":"支付密碼不能為空",
        "tip9":"密碼與支付密碼不能相同",
        "tip10":"確認登錄密碼與登錄密碼不壹致",
        "tip11":"修改成功",
        "tip12":"已提交，請等待後臺審核",
        "tip13":"綁定成功",
        "tip14":"修改成功",
        "tip15":"新密碼與確認密碼不壹致",
        "tip16":"支付密碼與不能與登錄密碼壹致",
        "tip17":"密碼錯誤",
        "tip18":"關閉成功",
        "tip19":"請輸入手機號",
        "tip20":"用戶不存在",
        "tip21":"請輸入郵箱",
        "tip22":"找回成功",
        "tip23":"找回類型不存在",
        "tip24":"請填寫提現地址",
        "tip25":"請填寫提現地址備註",
        "tip26":"請填寫支付密碼",
        "tip27":"添加成功",
        "tip28":"地址未選擇",
        "tip29":"提幣成功",
        "tip30":"請輸入昵稱",
        "tip31":"賬號或密碼錯誤",
        "register_tip":"註冊成功",
        //綁定
        "bind":"綁定",
        //商戶
        "alipay":"支付寶",
        "bank":"銀行",
        "wxpay":"微信",
        "dealin":"成交中",
        "submit_success":"提交成功",
        "completed":"已完成",
        "revoked":"已經撤銷",
        "revoke":"下線",
        //財務記錄
        "assets_to_fusion":"幣幣賬戶劃入聚變賬戶",
        "fusion_to_assets":"聚變賬戶劃出幣幣賬戶",
        "assets_to_c2c":"幣幣賬戶劃入法幣賬戶",
        "c2c_to_assets":"法幣賬戶劃出幣幣賬戶",
        "success":"成功",
        "failed":"失敗",
        "confirmation":"確認中",
        "locking":"鎖定",
        //行情
        "index_excpairs":"交易對",
        "index_latestprice":"最新價格",
        "index_zhuangfu":"今日漲幅",
        "index_maxprice":"最高價格",
        "index_minprice":"最低價格",
        "index_24H":"24H量",
        "index_24Htotal":"24H成交額",
        //首頁-下載
        "index_title1":"全球領先的加密貨幣去中心化交易平臺",
        "index_title2":"為全球100萬的專業加密貨幣投資者提供安全、穩定、高效的資產交易服務",
        "index_tip1":" <span>尖端安全防護</span><p>先進機器學習算法驅動的銀行級SSL安全技術，可主動檢測攻擊，保證您的資產和交易安全</p>",
        "index_tip2":" <span>閃電般的交易速度</span><p>3 秒完成訂單，與傳統中心化交易所媲美的速度。憑借 Getbit交易所 的先進共識機制，實現性能與安全雙重飛躍</p>",
        "index_tip3":" <span>全球服務支持</span><p>遍布美國、盧森堡、中國和新加坡的 Getbit交易所 團隊，為您提供全天候的服務支持</p>",
        "index_title3":"隨時隨地 多平臺終端交易",
        "index_title4":"覆蓋iOS、Android多個平臺，支持全業務功能",
        "index_title5":"IOS & Android 掃碼下載",
        "android_download":"Android 下載",
        "iphone_download":"iphone 下載",

        //登錄
        "login_right":'<h1 style="color: white">還沒有<br/>Getbit交易所賬號?</h1><p style="color: white">立即註冊,在Getbit交易所區塊鏈資產交易所進行交易。</p>',
        "login_toreg":"免費註冊",
        "login":"登錄 ",
        "login_account":"賬號",
        "login_accounts":"請輸入您的登錄賬號",
        "psw":"登錄密碼",
        "login_psws":"請輸入您的登錄密碼",
        "forget_password":"忘記密碼",
        "rememberme":"記住賬戶名",
        "regtime":"註冊時間",
        "login_tip2":"登錄成功",
        //註冊
        "register_right":'<p style="color: white">手機號與郵箱註冊後不可修改,請務必如實選擇。</p> <p style="color: white">驗證郵件可能會被誤判為垃圾郵件，請註意查收。</p><p style="color: white">請妥善保存您的Getbit交易所賬號及登錄密碼。</p><p style="color: white">請勿和其他網址使用相同的登錄密碼。</p>',
        "register_tosign":"立即登錄",
        "register_area":"區號",
        "register_account":"賬號",
        "phone":"手機",
        "imgcode":"圖片驗證",
        "phone_verifty":"驗證碼",
        "send":"發送驗證碼",
        "confirm_password":"確認登錄密碼",
        "deal_psw":"支付密碼",
        "invitecode":"邀請碼",
        "reg_tip":"請輸入郵箱或手機號",
        "noess":"非必填",
        //公告
        "news":"官方公告",
        "problem":"常見問題",
        "active":"最近活動",
        "createtime":"文章創建於",
        "search":"搜索",

        //忘記密碼
        "email":"郵箱",
        "forget_tip":"重置密碼後24小時禁止提幣。",
        "next":"下壹步",
        "prev":"上壹步",
        "newpassword":"新密碼",
        "forgettype":"找回類型",
        "phonetype":"電話找回",
        "pkeytype":"私鑰找回",
        "emailtype":"郵箱找回",
        "submit":"提交",
        //忘記支付密碼
        "cdeal_psw":"確認支付密碼",

        //資產
        "totalassets":"總資產折合",
        "proper_tip1":"隱藏數量為零的幣種",
        "searchcoin":"搜索幣種",
        "record":"財務記錄",
        "cashaddressmanage":"提現地址管理",
        "coins":"幣種",
        "total":"可用",
        "frozen":"凍結",
        "operation":"操作",
        "choosecoins":"選擇幣種",
        "cash_address":"提現地址",
        "cash_address_note":"提現地址備註",
        "cash_address_list":"提現地址列表",
        "del":"刪除",
        "wallet_address":"錢包地址",
        "copy":"點擊復制",
        "distinguish":"掃碼充幣",
        "tip":"溫馨提示",
        "tip_recharge1":"  <p>1、到賬時間壹般是10分鐘-60分鐘，如有疑問請聯繫help@gws.plus/</p>",
        "tip_recharge2":"  <p>2、您充值",
        "tip_recharge3":"上述地址後，需要整個",
        "tip_recharge4":"網絡節點的確認，為了快速到賬，您可以向",
        "tip_recharge5":"網絡支付少量的手續費。</p>",
        "tip_recharge6":"<p>3、最小充值金額是：0.01",
        "tip_recharge7":"您的",
        "tip_recharge8":"地址不會改變，可以重複充值，如有更改，我們會通過網站公告或郵件通知您。</p>",
        "rechargerecord":"充幣記錄",
        "date":"時間",
        "nums":"數量",
        "dnums":"到賬數量",
        "count":"確認數",
        "status":"狀態",
        "fee":"手續費",
        "fee_tip":"網絡手續費優先從賬戶余額中扣除，當余額不足網絡手續費時則從提幣數量中扣除",
        "rc":"記錄",
        "balance":"可用",
        "cash_tip":" <p>1. 最小提幣數量為：0.001",
        "cash_tip2":"</p><p>2. 為保障資金安全，當您賬戶安全策略變更、密碼修改、使用新地址提幣，我們會對提幣進行人工審核，請耐心等待工作人員電話或郵件聯系。</p><p>3. 請務必確認電腦及瀏覽器安全，防止信息被篡改或泄露。</p>",
        "cash_tip1":"您的提幣地址為空，點擊地址管理添加哦",
        "transfer":"劃轉",
        "fusion_transfer":"聚變劃轉",
        "noaddress":"暫無地址",
        //賬戶安全
        "safety":"安全認證",
        "cert":"認證",
        "safety_2":"安全級別",
        "auth":"實名認證",
        "google":"Google驗證",
        "unbound":"未綁定",
        "tobinding":"去綁定",
        "bound":"已綁定",
        "No_modifiable":"不可修改",
        "KYC_nc":"未完成KYC認證",
        "KYC_hc":"已完成KYC認證",
        "inaudit":"審核中",
        "reexamine":"重新審核",
        "tomodify":"去修改",
        "toclose":"去關閉",
        "close":"已關閉",
        "name":"姓名",
        "safety_tip1":"互聯網賬號存在被盜風險，建議您定期更改密碼以保護賬戶安全。",
        "safety_tip2":"強烈建議開啟3項安全認證",
        "safety_tip3":"用於提幣、找回密碼、修改安全設置、管理API時使用，激活後不可修改",
        "safety_tip4":"用於提幣、找回密碼、修改安全設置、管理API時用以收取驗證短信",
        "safety_tip5":"根據政策法規要求，請用戶務必實名認證，才能進行相關交易操作",
        "safety_tip6":"用於提幣、找回密碼、修改安全設置、管理API時用以輸入谷歌驗證碼",
        "login_history" :"登錄歷史",
        "security_settings_history" :"安全設置歷史",
        "time" :"時間",
        "login_method" :"登錄方式",
        "ip_address" :"IP地址",
        "security_setting" :"安全設置",
        "low":"低",
        "med":"中",
        "high":"高",
        //實名認證
        "auth_name":"真實姓名",
        "auth_type":"認證類型",
        "auth_type_1":"個人",
        "auth_type_2":"企業",
        "auth_number":"證件號碼",
        "auth_sfzzm":"上傳身份證正面照",
        "auth_sfzfm":"上傳身份證反面照",
        "auth_scsfz":"手持身份證",
        "auth_tip":"  <p>臉部清晰無遮擋</p><p>身份證全部清晰無遮擋</p><p>完全露出雙手手臂</p>",
        //重置密碼
        "resetpsw_tip":"請輸入原登錄密碼",
        "resetpsw":"修改登錄密碼",
        "resetdpsw":"修改支付密碼",
        "newpsw":"新密碼",
        //重置支付密碼
        "resetdpsw_tip":"請輸入原支付密碼",
        //商戶信息
        "pdegree":"好評度",
        "transtimes":"交易次數",
        "histurnover":"歷史成交額",
        "enumber":"評價數",
        "buy_adv":"購買廣告",
        "sell_adv":"出售廣告",
        "firm_coin":"幣種",
        "firm_scoin":"收款幣種",
        "price":"單價",
        "firm_translimit":"交易限額",
        "firm_transtype":"交易方式",
        "firm_updatetime":"最後更新時間",
        "firm_status":"廣告狀態",
        //訂單
        "all":"全部",
        "buy":"買單",
        "sell":"賣單",
        "nodata":"無數據",
        "excpairs":"交易對",
        "excpairsarea":"交易區",
        "transtype":"交易類型",
        "deal":"已成交",
        "nodeal":"未成交",
        //費率標準
        "rate_description" :"費率說明",
        "transaction_rate" :"交易費率",
        "withdrawal_rate" :"提現費率",
        "currency_pair" :"幣對",
        "buy_fee" :"買單手續費",
        "sell_fee" :"賣單手續費",
        "min_cash_nums" :"最小提幣數量",
        "cash_fee" :"提幣手續費",
        "rate_tip1":"充幣: 免費。",
        "rate_tip2":"交易: 普通用戶0.1% 的交易手續費（扣除收取到的資產）。",
        "rate_tip3":"提現: 提現手續費將會根據區塊實際情況定期調整",
        //我的邀請碼
        "invite_title":"<h1>Getbit交易所超級返傭</h1><h2>邀請好友交易，輕松獲得 20% 返傭</h2>",
        "mywayofsharing" :"我的分享方式",
        "qrposter" :"專屬二維碼海報",
        "view_exclusive_posters" :"查看專屬海報",
        "exclusive_invitation_code" :"專屬邀請碼",
        "exclusive_registration_link" :"專屬註冊鏈接",
        "total_invitations" :"邀請總人數",
        "invitation_record" :"邀請記錄",
        "invitee_account" :"被邀請人賬號",
        "registration_time" :"註冊時間",
        "remarks":"備註",
        //谷歌綁定
        "safety_verification" :"安全驗證",
        "bind_google_captcha" :"綁定谷歌驗證碼",
        "off_google_captcha":"關閉谷歌驗證碼",
        "google_captcha":"谷歌驗證碼",
        "google_secretkey":"密鑰",
        "copy_google_secretkey":"復制密鑰",
        "bind_goole_tips_1" :"谷歌驗證器是壹款動態口令工具，工作原理類似短信動態驗證。綁定後每30s生成壹個動態驗證碼，驗證碼可用於登錄、提現、修改安全設置",
        "bind_goole_tips_2" :"雙重驗證可以更安全的保護您的賬戶，未開啟雙重驗證不影響正常的交易。我們提供兩種綁定方式給用戶，用戶可以自行選擇並按流程操作",
        "bind_goole_tips_3" :"綁定谷歌驗證器",
        "bind_goole_tips_4" :'IOS用戶登錄App Store搜索"Authenticator"下載。',
        "bind_goole_tips_5" :'安卓用戶登錄應用商店或使用手機瀏覽器搜索"谷歌驗證器"下載',
        "bind_goole_tips_6" :"在新谷歌驗證器中添加以下新密鑰並備份",
        "bind_goole_tips_7" :"打開谷歌驗證器，掃描下方二維碼或手動輸入下述密鑰添加驗證令牌。",
        "bind_goole_tips_8" :"密鑰用於手機更換或遺失時找回谷歌驗證器，綁定前請務必將下述密鑰備份保存。",
        "bind_goole_tips_9" :"請輸入谷歌驗證碼",
        "bind_goole_tips_10":"在新谷歌驗證器中添加以下新密鑰並備份",
        //wap
        "phonenumber" :"手機號",
        "wap_reg_title" :"手機號註冊",
        "wap_reg_title_2" :"郵箱註冊",
        "wap_reg_tip1" :"使用常用手機號進行註冊，更便捷",
        "wap_reg_tip_1" :"使用常用郵箱進行註冊，更便捷",
        "wap_to_phone" :"去用手機註冊",
        "wap_to_email" :"去用郵箱註冊",
        "wap_reg_tip2" :"註冊代表同意",
        "wap_reg_tip3" :"《本平臺用戶協議》",
        "wap_reg_tip4" :"已有賬號？",
        "sms_code" :"短信驗證碼",
        "sms_code2" :"郵箱驗證碼",
        "wap_reg_tip5" :"驗證碼已發送到妳的手機",
        "wap_reg_tip_5" :"驗證碼已發送到妳的郵箱",
        "wap_reg_tip6" :"沒有收到驗證碼？",
        "wap_reg_title1" :"創建密碼",
        "wap_reg_tip7" :"創建登錄密碼可增強資產安全性，用於登錄賬號",
        "wap_reg_title2" :"創建支付密碼",
        "wap_reg_tip8" :"創建支付密碼可增強資產安全性",
        "wap_reg_title3" :"邀請碼",
        "wap_reg_tip9" :"請輸入正確的邀請碼格式",
        "wap_reg_complete" :"完成註冊",
        "wap_reg_tip10" :"請輸入6-16位字母數字組合",
        "wap_reg_tip11" :"請確認登錄密碼",
        "wap_reg_tip12" :"請輸入6位純數字",
        "wap_reg_tip13" :"請確認支付密碼",
        "wap_reg_tip14" :"請輸入邀請碼"
}
export default zhTw